include:
  - ./templates/networks.yml

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.3
    container_name: nginx-proxy-manager
    env_file:
      - ./services/gateway/nginx-proxy-manager/.env.local
    volumes:
      - ./volumes/gateway/nginx-proxy-manager/data:/data:rw
      - ./volumes/gateway/nginx-proxy-manager/custom:/data/nginx/custom:rw
      - ./volumes/gateway/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:rw
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 32M
        limits:
          memory: "${SERVICE_GATEWAY_NGINX_PROXY_MANAGER_MEMORY_LIMITS:?}"
    expose:
      - 80
      - 443
      - 81
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - home-network
    restart: unless-stopped
