services:
  timemachine:
    image: mbentley/timemachine:smb-20251012
    container_name: timemachine
    env_file:
      - ./services/backup/timemachine/.env.local
    network_mode: "host"
    volumes:
      - ${BACKUP_TIMEMACHINE_SMB_DIR:?}:/opt/timemachine
    tmpfs:
      - /run/samba
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          memory: "${SERVICE_BACKUP_TIMEMACHINE_MEMORY_LIMITS:?}"
    restart: unless-stopped
