global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'

  - job_name: 'node-exporter-proxy'
    static_configs:
      - targets: ['192.168.1.62:9100']
        labels:
          instance: 'proxy'

  - job_name: 'cadvisor-proxy'
    static_configs:
      - targets: ['192.168.1.62:9200']
        labels:
          instance: 'proxy'

  - job_name: 'node-exporter-infra'
    static_configs:
      - targets: ['192.168.1.106:9100']
        labels:
          instance: 'infra'

  - job_name: 'cadvisor-infra'
    static_configs:
      - targets: ['192.168.1.106:9200']
        labels:
          instance: 'infra'

  - job_name: 'node-exporter-observability'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'observability'

  - job_name: 'cadvisor-observability'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'observability'
