global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus.yml'

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - 'node-exporter.yml'

  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - 'cadvisor.yml'

  - job_name: 'smartctl-exporter'
    file_sd_configs:
      - files:
          - 'smartctl-exporter.yml'
