include:
  - ./templates/networks.yml

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    env_file:
      - ./services/media/flaresolverr/.env.local
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8191/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 64M
        limits:
          memory: "${SERVICE_MEDIA_FLARESOLVERR_MEMORY_LIMITS:?}"
    expose:
      - 8191
      - 8192
    networks:
      - home-network
    restart: unless-stopped
