services:
  plex:
    image: plexinc/pms-docker:1.42.1.10060-4e8b05daf
    container_name: plex
    network_mode: host
    env_file:
      - ./services/media/plex/.env.local
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:32400/web || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          memory: "${SERVICE_MEDIA_PLEX_MEMORY_LIMITS:?}"
    volumes:
      - ./volumes/media/plex/transcode:/transcode
      - ./volumes/media/plex/config:/config
      - ${MEDIA_PLEX_SMB_DIR:?}:/data
    restart: unless-stopped
