include:
  - ./templates/networks.yml
  - ./templates/volumes-media.yml

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.13.2932-ls273
    container_name: sonarr
    env_file:
      - ./services/media/sonarr/.env.local
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8989/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 64M
        limits:
          memory: "${SERVICE_MEDIA_SONARR_MEMORY_LIMITS:?}"
    volumes:
      - sonarr-config:/config
      - ${MEDIA_PLEX_SMB_DIR:?}:/data
    expose:
      - 8989
    ports:
      - ${MEDIA_SONARR_PORT:?}:8989
    networks:
      - home-network
    restart: unless-stopped

